# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- developer
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(date:yyyy).$(Month)$(rev:.r)

steps:

- script: yarn install

- task: Gradle@2
  displayName: 'Build Android'
  inputs:
    gradleWrapperFile: 'android/gradlew'
    workingDirectory: 'android'
    options: '-PversionName=$(Build.BuildNumber) -PversionCode=$(Build.BuildId)'
    tasks: 'assembleDevRelease'
    publishJUnitResults: false
    gradleOptions: '-Xmx3072m'

- task: AndroidSigning@3
  displayName: 'Android Signing'
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'mykeystore.keystore'
    apksignerKeystorePassword: '$(MYAPP_RELEASE_STORE_PASSWORD)'
    apksignerKeystoreAlias: 'mykeyalias'
    apksignerKeyPassword: '$(MYAPP_RELEASE_KEY_PASSWORD)'
    zipalign: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'android/app/build/outputs/bundle/devrelease'
    ArtifactName: 'drop'
    publishLocation: 'Container'
